# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stuart Wiener
email: hello@stuartwiener.com
description: Stuart Wiener is an experience designer and design thinker living and working in Johannesburg, South Africa
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stuartwiener.com" # the base hostname & protocol for your site
twitter_username: stuartwiener
github_username:  stuartwiener

# Build settings
markdown: kramdown
